'use client';

import { useState } from 'react';
import { 
  Share2, 
  FileText, 
  Code, 
  Globe, 
  Mail, 
  Twitter, 
  Linkedin, 
  Facebook,
  Copy,
  FileDown
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
} from '@/components/ui/dropdown-menu';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { type Message } from '@/lib/types';
import { toast } from 'sonner';
import { exportMessageToPDF } from '@/lib/pdf-export';

interface MessageShareProps {
  message: Message;
  className?: string;
}

export function MessageShare({ message, className }: MessageShareProps) {
  const [isSharing, setIsSharing] = useState(false);

  // Convert message to plain text
  const toPlainText = (): string => {
    return message.content;
  };

  // Convert message to markdown
  const toMarkdown = (): string => {
    const timestamp = message.createdAt 
      ? new Date(message.createdAt).toLocaleString() 
      : '';
    
    let markdown = `# AI Response\n\n`;
    if (timestamp) {
      markdown += `**Date:** ${timestamp}\n\n`;
    }
    if (message.modelUsed) {
      markdown += `**Model:** ${message.modelUsed}\n\n`;
    }
    markdown += `---\n\n${message.content}\n\n`;
    markdown += `---\n\n*Generated by SOHAM - https://soham-ai.vercel.app*`;
    
    return markdown;
  };

  // Convert message to HTML
  const toHTML = (): string => {
    const timestamp = message.createdAt 
      ? new Date(message.createdAt).toLocaleString() 
      : '';
    
    // Simple markdown to HTML conversion
    let html = message.content
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.*?)\*/g, '<em>$1</em>')
      .replace(/`(.*?)`/g, '<code>$1</code>')
      .replace(/\n\n/g, '</p><p>')
      .replace(/\n/g, '<br>');
    
    return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AI Response - SOHAM</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
      color: #333;
    }
    .header {
      border-bottom: 2px solid #e5e7eb;
      padding-bottom: 10px;
      margin-bottom: 20px;
    }
    .meta {
      color: #6b7280;
      font-size: 0.875rem;
      margin-bottom: 10px;
    }
    .content {
      margin: 20px 0;
    }
    code {
      background: #f3f4f6;
      padding: 2px 6px;
      border-radius: 4px;
      font-family: 'Courier New', monospace;
    }
    .footer {
      border-top: 2px solid #e5e7eb;
      padding-top: 10px;
      margin-top: 30px;
      text-align: center;
      color: #6b7280;
      font-size: 0.875rem;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>AI Response</h1>
    ${timestamp ? `<div class="meta">Date: ${timestamp}</div>` : ''}
    ${message.modelUsed ? `<div class="meta">Model: ${message.modelUsed}</div>` : ''}
  </div>
  <div class="content">
    <p>${html}</p>
  </div>
  <div class="footer">
    Generated by <strong>SOHAM</strong><br>
    <a href="https://soham-ai.vercel.app">https://soham-ai.vercel.app</a>
  </div>
</body>
</html>`;
  };

  // Download file
  const downloadFile = (content: string, filename: string, mimeType: string) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success(`Downloaded as ${filename}`);
  };

  // Export handlers
  const handleExportText = () => {
    const content = toPlainText();
    downloadFile(content, 'ai-response.txt', 'text/plain');
  };

  const handleExportMarkdown = () => {
    const content = toMarkdown();
    downloadFile(content, 'ai-response.md', 'text/markdown');
  };

  const handleExportHTML = () => {
    const content = toHTML();
    downloadFile(content, 'ai-response.html', 'text/html');
  };

  // Export to PDF
  const handleExportPDF = async () => {
    try {
      toast.info('Preparing PDF export...');
      await exportMessageToPDF({
        message,
        includeMetadata: true,
        includeBranding: true,
      });
      toast.success('PDF export ready! Use your browser\'s print dialog to save.');
    } catch (error) {
      console.error('PDF export error:', error);
      toast.error('Failed to export PDF');
    }
  };

  // Copy to clipboard
  const handleCopyFormatted = async (format: 'text' | 'markdown' | 'html') => {
    let content = '';
    switch (format) {
      case 'text':
        content = toPlainText();
        break;
      case 'markdown':
        content = toMarkdown();
        break;
      case 'html':
        content = toHTML();
        break;
    }
    
    await navigator.clipboard.writeText(content);
    toast.success(`Copied as ${format.toUpperCase()}`);
  };

  // Share via email
  const handleEmailShare = () => {
    const subject = encodeURIComponent('AI Response from SOHAM');
    const body = encodeURIComponent(
      `${toPlainText()}\n\n---\nGenerated by SOHAM\nhttps://soham-ai.vercel.app`
    );
    window.open(`mailto:?subject=${subject}&body=${body}`, '_blank');
  };

  // Share on social media
  const handleSocialShare = (platform: 'twitter' | 'linkedin' | 'facebook') => {
    const text = message.content.substring(0, 200) + (message.content.length > 200 ? '...' : '');
    const url = 'https://soham-ai.vercel.app';
    
    let shareUrl = '';
    switch (platform) {
      case 'twitter':
        shareUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`;
        break;
      case 'linkedin':
        shareUrl = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`;
        break;
      case 'facebook':
        shareUrl = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`;
        break;
    }
    
    window.open(shareUrl, '_blank', 'width=600,height=400');
  };

  // Native share (mobile)
  const handleNativeShare = async () => {
    if (typeof window === 'undefined' || !('share' in navigator)) {
      toast.error('Sharing not supported on this device');
      return;
    }

    setIsSharing(true);
    try {
      await navigator.share({
        title: 'AI Response from SOHAM',
        text: toPlainText(),
        url: 'https://soham-ai.vercel.app',
      });
      toast.success('Shared successfully');
    } catch (error: any) {
      if (error.name !== 'AbortError') {
        toast.error('Failed to share');
      }
    } finally {
      setIsSharing(false);
    }
  };

  return (
    <TooltipProvider delayDuration={100}>
      <DropdownMenu>
        <Tooltip>
          <TooltipTrigger>
            <DropdownMenuTrigger asChild>
              <Button
                variant="ghost"
                size="icon"
                className={className}
                disabled={isSharing}
              >
                <Share2 className="h-3.5 w-3.5" />
              </Button>
            </DropdownMenuTrigger>
          </TooltipTrigger>
          <TooltipContent>
            <p>Share & Export</p>
          </TooltipContent>
        </Tooltip>

        <DropdownMenuContent align="end" className="w-56">
          <DropdownMenuLabel>Download Formats</DropdownMenuLabel>
          
          <DropdownMenuItem onClick={handleExportPDF}>
            <FileDown className="mr-2 h-4 w-4 text-blue-500" />
            <span className="font-medium">Export as PDF</span>
          </DropdownMenuItem>
          
          <DropdownMenuItem onClick={handleExportHTML}>
            <Globe className="mr-2 h-4 w-4 text-orange-500" />
            <span className="font-medium">Export as HTML</span>
          </DropdownMenuItem>
          
          <DropdownMenuItem onClick={handleExportText}>
            <FileText className="mr-2 h-4 w-4 text-green-500" />
            <span className="font-medium">Export as Text</span>
          </DropdownMenuItem>
          
          <DropdownMenuItem onClick={handleExportMarkdown}>
            <Code className="mr-2 h-4 w-4 text-purple-500" />
            <span>Export as Markdown</span>
          </DropdownMenuItem>

          <DropdownMenuSeparator />
          
          <DropdownMenuLabel>Quick Copy</DropdownMenuLabel>
          
          <DropdownMenuItem onClick={() => handleCopyFormatted('text')}>
            <Copy className="mr-2 h-4 w-4" />
            <span>Copy as Text</span>
          </DropdownMenuItem>
          
          <DropdownMenuItem onClick={() => handleCopyFormatted('markdown')}>
            <Copy className="mr-2 h-4 w-4" />
            <span>Copy as Markdown</span>
          </DropdownMenuItem>

          <DropdownMenuSeparator />
          
          <DropdownMenuLabel>Share Options</DropdownMenuLabel>
          
          <DropdownMenuItem onClick={handleEmailShare}>
            <Mail className="mr-2 h-4 w-4" />
            <span>Share via Email</span>
          </DropdownMenuItem>

          <DropdownMenuSub>
            <DropdownMenuSubTrigger>
              <Share2 className="mr-2 h-4 w-4" />
              <span>Share on Social</span>
            </DropdownMenuSubTrigger>
            <DropdownMenuSubContent>
              <DropdownMenuItem onClick={() => handleSocialShare('twitter')}>
                <Twitter className="mr-2 h-4 w-4" />
                <span>Twitter</span>
              </DropdownMenuItem>
              <DropdownMenuItem onClick={() => handleSocialShare('linkedin')}>
                <Linkedin className="mr-2 h-4 w-4" />
                <span>LinkedIn</span>
              </DropdownMenuItem>
              <DropdownMenuItem onClick={() => handleSocialShare('facebook')}>
                <Facebook className="mr-2 h-4 w-4" />
                <span>Facebook</span>
              </DropdownMenuItem>
            </DropdownMenuSubContent>
          </DropdownMenuSub>

          {typeof window !== 'undefined' && 'share' in navigator && (
            <>
              <DropdownMenuSeparator />
              <DropdownMenuItem onClick={handleNativeShare}>
                <Share2 className="mr-2 h-4 w-4" />
                <span>Share via Device</span>
              </DropdownMenuItem>
            </>
          )}
        </DropdownMenuContent>
      </DropdownMenu>
    </TooltipProvider>
  );
}
